### ISSUE TITLE
Exercise not marked as done

### ISSUE THREAD

**Issue by Berelarsenp** [rmotr-curriculum/base-python-curriculum#10]
I've done "Zip two collections" in another Unit and I did it again, but no matter what, the circle in this screen does not turns blue, so it appears as not completed. ![captura de pantalla de 2018-03-04 18-38-28](https://user-images.githubusercontent.com/22670036/36950883-5c7bd93c-1fdb-11e8-87d4-38356df1698f.png)
![captura de pantalla de 2018-03-04 18-39-53](https://user-images.githubusercontent.com/22670036/36950890-7749c1fc-1fdb-11e8-95bd-4d55b6939864.png)

**Comment by jasonmeeks** [comment]
Yeah, we moved it to a different location and I guess there was a bug. I'll let santa know! thanks for the feedback

**Comment by Berelarsenp** [comment]
No, thanks to you for being awesome! :)

El 7 mar. 2018 15:30, "jasonmeeks" <notifications@github.com> escribió:

Yeah, we moved it to a different location and I guess there was a bug. I'll
let santa know! thanks for the feedback

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rmotr-curriculum/base-python-curriculum/issues/10#issuecomment-371231142>,
or mute the thread

**Comment by santiagobasulto** [comment]
Sorry for the late update, but this should be working now.
