### ISSUE TITLE
primes? 

### ISSUE THREAD

**Issue by irina-bourry** [rmotr-curriculum/base-python-curriculum#13]
Excuse me, slight issue with the test cases - you want us to return 'True' for the is_prime function regardless of the input, same issue for is_not_prime.

**Comment by santiagobasulto** [comment]
Hello @irina-bourry ! What assignment do you mean?

**Comment by irina-bourry** [comment]
Hey @santiagobasulto :) I was talking about Palindromic Primes but never mind, I figured it out, it was me. 

Where is the best place to ask questions? Is it the slack? I posted some issues there, they are not urgent though. 

Cheers!

**Comment by santiagobasulto** [comment]
Hello Irina! In your Student's Profile, you should see a section to reach the questions:
![image](https://user-images.githubusercontent.com/872296/37308892-112e3fc6-261e-11e8-8fd7-eb7773ce04ca.png)
