### ISSUE TITLE
Assignment "Search keys for a value" depends on sets before taught

### ISSUE THREAD

**Issue by jsymons** [rmotr-curriculum/base-python-curriculum#18]
Continued from https://github.com/rmotr-curriculum/base-python-curriculum/issues/8

Ok so I've had this come up again w/ the new batch of students. This assignment is listed with a suggested start date of before they have class 2 of unit 2, so this should either be moved to after module 3 (Intro to Sets), or after class 2 of unit 2 (module 6, which is the class that sets take place in.
![selection_001](https://user-images.githubusercontent.com/11019465/37489667-be950652-286e-11e8-87d2-5463e22d6b43.png)

See https://github.com/rmotr-curriculum/base-python-curriculum-questions/issues/49

**Comment by santiagobasulto** [comment]
Amazing, thanks.
