### ISSUE TITLE
Can be improved

### ISSUE THREAD

**Issue by renjuzac** [rmotr-curriculum/base-python-curriculum#23]
Instructions are confusing 
Test cases are out of order when compared with the problems in the code section
The task in the code section is the same problem repeated over and over
Also , the test cases cannot be run individually till everything is completed due to the ? in the code section.
Please consider fixing.

**Comment by santiagobasulto** [comment]
Hello @renjuzac! Your code always need to be complete to run the tests, it's not something we can "fake". What instructions are confusing? We can improve them if you point at them.

We know that when you're just starting, things might not make a lot of sense. But we have hundreds of students all using these methods and they're all learning with it. We're showing you the way coding actually works (with tests and TDD, with different python versions, correct data types, etc).
