### ISSUE TITLE
Typo in Lesson 7/13: "In or Out" 

### ISSUE THREAD

**Issue by Horsecrazygirl42** [rmotr-curriculum/base-python-curriculum#24]
"In or out
The in keyword is used to determine **is** something is part of something else."

**is** should say **if**

thanks! :)

**Comment by santiagobasulto** [comment]
Thanks for reporting it!

**Comment by santiagobasulto** [comment]
Fixed in https://github.com/rmotr-curriculum/base-python-curriculum/commit/8f1e91de7c2794d0aad44041fc4dca558599ae18
