### ISSUE TITLE
Typo on Invoking Functions Lesson

### ISSUE THREAD

**Issue by f-mac** [rmotr-curriculum/base-python-curriculum#26]
Intro to Functions -- > Invoking Functions

Have a double 'is'.

> The fancy tech name we give to the action of "using" a function **is is** "invoke a function".

**Comment by santiagobasulto** [comment]
Fixed here: https://github.com/rmotr-curriculum/base-python-curriculum/commit/72f1bf37d9f481dd231ebf511a6ae526b01b42a4

Thanks!
