### ISSUE TITLE
Not showing completion

### ISSUE THREAD

**Issue by cpjain2007** [rmotr-curriculum/base-python-curriculum#35]
Even though I submitted a solution for "Valid Passwords" from Unit 1 "Getting Started" it is not showing completed in my profile. Not a big thing though. 

thanks

**Comment by santiagobasulto** [comment]
Checking right now! Thanks @cpjain2007 !

**Comment by santiagobasulto** [comment]
Fixed @cpjain2007! Thanks for your patience 😌
