### ISSUE TITLE
Infinite processing

### ISSUE THREAD

**Issue by jjk235** [rmotr-curriculum/base-python-curriculum#39]
Hi there. Every time I click 'run code' or 'submit solution' the icon changes to indicate that it's processing the request but nothing happens afterwords, just the icon spinning in place.

**Comment by santiagobasulto** [comment]
Hey @jjk235, checking and restarting everything just in case. can you try now?

**Comment by jjk235** [comment]
Hi Santiago, thanks for reaching out. I've restarted everything and it's all worked out. I can't believe I'm now 'that' guy who didn't restart everything before contacting support! I appreciate that you took the time to reply :)


Jae


________________________________

**Comment by santiagobasulto** [comment]
Haha, no problem! Glad it worked 😄
