### ISSUE TITLE
tested the code which gives both True but with pratice it's giving wrong result.

### ISSUE THREAD

**Issue by aashishkhanal** [rmotr-curriculum/base-python-curriculum#4]
you_shall_pass = not True
the_time_is_now = "a" in "apple"
false_variable = False

# Use `and` to check if you_shall_pass and the_time_is_now both evaluate to true
result1 = you_shall_pass is False and  the_time_is_now is True

# Now use two `and`s to combine all three variables at the top, and use your knowledge of `not` to make this and statement result be True
result2 = you_shall_pass is False and the_time_is_now is not False and false_variable is not True

**Comment by santiagobasulto** [comment]
Hello @aashishkhanal what assignment were you using?
