### ISSUE TITLE
Assignment "Search keys for a value" depends on sets before they are taught

### ISSUE THREAD

**Issue by jsymons** [rmotr-curriculum/base-python-curriculum#8]
Assignment: https://github.com/rmotr-curriculum/base-python-curriculum/tree/master/unit-9-collections-part-2/lesson-12-search-keys-for-value

Should be moved from unit 2, class 2, module 2 to unit 2, class 2, module 4 as module 3 is where we introduce sets.

**Comment by jasonmeeks** [comment]
we actually introduce sets class 2 of unit 2 now so this should be good. good eye though! glad someone is keeping track of this

**Comment by jsymons** [comment]
Ok so I've had this come up again w/ the new batch of students. This assignment is listed with a suggested start date of before when they have class 2 of unit 2, so this should either be moved to after module 3 (Intro to Sets), or after class 2 of unit 2 (module 6, which is the class that sets take place in.
![selection_001](https://user-images.githubusercontent.com/11019465/37489667-be950652-286e-11e8-87d2-5463e22d6b43.png)
